### ISSUE TITLE
web archiving crawl objects need integration tests

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#15] opened 2020-02-24 22:10 UTC
- test for creating new web archiving crawl object in SDR
- test for updating SDR web archival crawl object with new data (?)

The test should mimic what is done for was-crawl object (e.g. start in was-registrar-app?) and should check for was crawl object-ness in Argo.  We would like to run something through the was robots if we can (might be hard - crawls can be biiiiig ... i wonder if we can set up a fixture tiny warc file or borrow an existing one from was-robots-suite.

Want to test all the way through accessioning (was-robot-suite and common-accessioning) if that is possible, and definitely check for was crawl object-ness in Argo.  

Talk to Andrew, and ask in web-archiving slack channel.

**Comment by justinlittman** [comment] 2020-04-03 11:29
The challenge for a web archiving crawl object is that a WASAPI provider is needed to provide a unique response to a query. Currently, Internet Archive is our only WASAPI provider, which will not provide a new WARC for every run of the integration test.

One option to consider is creating a mock WASAPI provider (perhaps running directly in the app) that does provide an appropriate response.

**Comment by mjgiarlo** [comment] 2022-06-09 18:24
Duplicate of #434

**Closed by mjgiarlo** 2022-06-09 18:24 UTC
Labels: web archiving
